default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: score_app_development

test:
  <<: *default
  database: score_app_test

production:
  <<: *default
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  database: myapp_productio
