default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: score_app_development

test:
  <<: *default
  database: score_app_test

production:
  <<: *default
  database: score_app_production
  username: score_app
  password: <%= ENV['SCORE_APP_DATABASE_PASSWORD'] %>
